- name: Set authorized key taken from file
  authorized_key:
    key: "{{ lookup('file', '/home/demay/.ssh/terraform.pub') }}"


- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: no


# - name: Upgrade all packages to the latest version
#   apt:
#     name: "*"
#     state: latest
#     update_cache: yes
#     become_user: root 

- name: Install apache httpd but avoid starting it immediately (state=present is optional)
  apt:
    name: apache2
    state: present
    become: yes
  environment:
    RUNLEVEL: 1   